spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 01
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  liquibase:  #Нужна для контроля Базы данных
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true